# https://github.com/mjgardner/svn-simple-hook/blob/master/.travis.yml

language: perl
install:
  # Listing of project dependencies may require some author tools.
  - dzil authordeps | cpanm --notest
  - dzil listdeps | cpanm --notest
  - cpanm --notest Test::Perl::Critic Test::CPAN::Meta Pod::Coverage::TrustPod
  # TODO: find Australian/British English dictionary, so things like
  # "online," "cheque" and "dishonoured" are deemed acceptable.
  # - sudo apt-get install aspell
script: dzil test --verbose --release
